CREATE TABLE TB_USER (
    USER_ID VARCHAR2(20) CONSTRAINT USERID_PK PRIMARY KEY,  
    USER_NAME VARCHAR2(20) CONSTRAINT USERNAME_NN NOT NULL, 
    BIRTYEAR NUMBER,       
    ADDR CHAR(20),           
    MOBILE VARCHAR2(13) CONSTRAINT MOBILE_NN NOT NULL UNIQUE,    
    HEIGHT NUMBER CHECK(HEIGHT > 0),     
    USER_DATE DATE   
);
SELECT *
FROM TB_USER;

DROP TABLE TB_USER;

COMMENT ON COLUMN TB_USER.USER_ID IS '사용자아이디';
COMMENT ON COLUMN TB_USER.USER_NAME IS '사용자이름';
COMMENT ON COLUMN TB_USER.BIRTYEAR IS '출생연도';
COMMENT ON COLUMN TB_USER.ADDR IS '지역';
COMMENT ON COLUMN TB_USER.MOBILE IS '전화번호';
COMMENT ON COLUMN TB_USER.HEIGHT IS '키';
COMMENT ON COLUMN TB_USER.USER_DATE IS '회원가입일';

INSERT INTO TB_USER VALUES('ayj', '안유진', 2003, '대전광역시', '010-0109-2580', 172, '21/12/01');
INSERT INTO TB_USER VALUES('lyj', '이영지', null, '서울특별시', '010-0941-6321', 175, '19/11/02');
INSERT INTO TB_USER VALUES('lej', '이은지', 1992, 'null', '010-1016-5624', 161, '14/06/09');
INSERT INTO TB_USER VALUES('mimi', '미미', 1995, '제주도', '010-5101-8891', 164, '15/04/20');

------------------------------------------------------------------------------------------------
CREATE TABLE TB_PRODUCT(
    PRODUCT_CODE VARCHAR2(20) PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(20) NOT NULL,
    PRODUCT_GROUP VARCHAR2(20),
    PRICE NUMBER NOT NULL,
    AMOUNT NUMBER
);

SELECT *
FROM TB_PRODUCT;

COMMENT ON COLUMN TB_PRODUCT.PRODUCT_CODE













