SELECT SYSDATE
FROM DUAL;

SELECT LENGTH('오라클'), LENGTHB('오라클')
FROM DUAL;

SELECT LENGTH('oracle'), LENGTHB('oracle')
FROM DUAL;

SELECT EMP_NAME, LENGTH(EMP_NAME), LENGTHB(EMP_NAME)
FROM EMPLOYEE;

SELECT EMAIL, LENGTH(EMAIL), LENGTHB(EMAIL)
FROM EMPLOYEE;

SELECT INSTR('AABAACAABBAA', 'B')
FROM DUAL;

SELECT INSTR('AABAACAABBAA', 'B', 1)
FROM DUAL;

SELECT INSTR('AABAACAABBAA', 'B', -1)
FROM DUAL;

SELECT INSTR('AABAACAABBAA', 'B', 1, 2)
FROM DUAL;

SELECT INSTR('AABAACAABBAA', 'B', -1, 3)
FROM DUAL;

SELECT EMAIL, INSTR(EMAIL, '_', 1, 1) AS "_위치", INSTR(EMAIL, '@') AS "@위치"
FROM EMPLOYEE;

SELECT SUBSTR('MERRYCHRISTMAS', 6)
FROM DUAL;

SELECT SUBSTR('MERRYCHRISTMAS', 6, 6)
FROM DUAL;

SELECT SUBSTR('MERRYCHRISTMAS', 1, 5)
FROM DUAL;

SELECT SUBSTR('MERRYCHRISTMAS', -9, 5)
FROM DUAL;

SELECT EMP_NAME, EMP_NO, SUBSTR(EMP_NO, 8, 1) AS "성별"
FROM EMPLOYEE;

SELECT EMP_NAME, EMP_NO
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO, 8, 1) IN ('2', '4');

SELECT EMP_NAME, EMP_NO
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO, 8, 1) IN ('1', '3')
ORDER BY EMP_NO;

SELECT EMP_NAME, EMAIL, SUBSTR(EMAIL, 1, INSTR(EMAIL, '@') - 1) AS "아이디"
FROM EMPLOYEE
ORDER BY "아이디";

SELECT EMP_NAME, LPAD(SUBSTR(EMAIL, 1, INSTR(EMAIL, '@') - 1), 10, '-') AS "아이디"
FROM EMPLOYEE
ORDER BY "아이디";

SELECT ROUND(144.852)
FROM DUAL;

SELECT ROUND(144.852, 1)
FROM DUAL;

SELECT ROUND(144.852, -1)
FROM DUAL;

SELECT ROUND(144.852, -2)
FROM DUAL;

SELECT CEIL(154.852)
FROM DUAL;

SELECT FLOOR(185.852)
FROM DUAL;

SELECT FLOOR(185.352)
FROM DUAL;

SELECT TRUNC(154.852)
FROM DUAL;

SELECT TRUNC(154.852, 1)
FROM DUAL;

SELECT TRUNC(154.825, 1)
FROM DUAL;

SELECT TRUNC(154.852, -1)
FROM DUAL;

SELECT SYSDATE
FROM DUAL;

SELECT EMP_NAME, SYSDATE - HIRE_DATE
FROM EMPLOYEE;

SELECT EMP_NAME, FLOOR(SYSDATE - HIRE_DATE) || '일' AS "근무일수",
CEIL(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) || '개월' AS "근무개월수"
FROM EMPLOYEE;

SELECT EMP_NAME, FLOOR(SYSDATE - HIRE_DATE) || '일' AS "근무일수",
FLOOR(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) || '개월' AS "근무개월수"
FROM EMPLOYEE;

SELECT EMP_NAME, FLOOR(SYSDATE - HIRE_DATE) || '일' AS "근무일수",
TRUNC(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) || '개월' AS "근무개월수"
FROM EMPLOYEE;

SELECT EMP_NAME, FLOOR(SYSDATE - HIRE_DATE) || '일' AS "근무일수",
ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) || '개월' AS "근무개월수"
FROM EMPLOYEE;

SELECT ADD_MONTHS(SYSDATE, 1)
FROM DUAL;

SELECT EMP_NAME, HIRE_DATE, ADD_MONTHS(HIRE_DATE, 3) AS "수습이 끝난 날짜"
FROM EMPLOYEE
ORDER BY "수습이 끝난 날짜";

SELECT SYSDATE, NEXT_DAY(SYSDATE, '월요일')
FROM DUAL;

SELECT SYSDATE, NEXT_DAY(SYSDATE, '화')
FROM DUAL;

SELECT SYSDATE, NEXT_DAY(SYSDATE, 1)
FROM DUAL;

SELECT EMP_NAME, HIRE_DATE, LAST_DAY(HIRE_DATE)
FROM EMPLOYEE;

SELECT EMP_NAME, HIRE_DATE, LAST_DAY(HIRE_DATE) - HIRE_DATE
FROM EMPLOYEE;

SELECT EMP_NAME, CEIL(LAST_DAY(SYSDATE) - HIRE_DATE)
FROM EMPLOYEE;

SELECT EMP_NAME,
EXTRACT(YEAR FROM HIRE_DATE) || '년' AS "입사년도",
EXTRACT(MONTH FROM HIRE_DATE) || '월' AS "입사월",
EXTRACT(DAY FROM HIRE_DATE) || '일' AS "입사일"
FROM EMPLOYEE
ORDER BY "입사년도", "입사월", "입사일";

SELECT TO_CHAR(1234)
FROM DUAL;

SELECT TO_CHAR(1234, '999999')
FROM DUAL;

SELECT TO_CHAR(5678, '000000')
FROM DUAL;

SELECT TO_CHAR(5678, 'L000000')
FROM DUAL;

SELECT TO_CHAR(5678, 'L999999')
FROM DUAL;

SELECT TO_CHAR(5678, '$999999')
FROM DUAL;

SELECT TO_CHAR(SALARY, '9999999')
FROM EMPLOYEE;

SELECT TO_CHAR(SALARY, '999,999,999')
FROM EMPLOYEE;

SELECT TO_CHAR(SALARY, 'L999,999,999')
FROM EMPLOYEE;

SELECT SYSDATE
FROM DUAL;

SELECT TO_CHAR(SYSDATE)
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'HH:MI:SS')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'HH24:MI:SS')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'AM HH:MI:SS')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD DAY')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'MON, YYYY')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD DAY AM HH:MI:SS')
FROM DUAL;













